/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vut.gui;

import java.text.NumberFormat;
import javax.swing.*;
import vut.ProductSales;

/**
 *
 * @author samkelo
 */
public class Productsale extends javax.swing.JFrame
{

    ProductSales objProductSales = new ProductSales();
    
    /**
     * Creates new form Productsale
     */
    public Productsale()
    {
        initComponents();
        GroupButton();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblCustomerName = new javax.swing.JLabel();
        lblProductName = new javax.swing.JLabel();
        lblProductPrice = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        lblIsMemeber = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        txtProductName = new javax.swing.JTextField();
        txtProductPrice = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        rbnYes = new javax.swing.JRadioButton();
        rbnNo = new javax.swing.JRadioButton();
        btnProcess = new javax.swing.JButton();
        btnClearForm = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taInvoice = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("218124031");

        lblCustomerName.setText("Customer Name :");

        lblProductName.setText("Product Name:");

        lblProductPrice.setText("Product Price :");

        lblQuantity.setText("Quantity");

        lblIsMemeber.setText("Is Member");

        rbnYes.setText("Yes");

        rbnNo.setText("No");

        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnProcessActionPerformed(evt);
            }
        });

        btnClearForm.setText("Clear Form");
        btnClearForm.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnClearFormActionPerformed(evt);
            }
        });

        taInvoice.setColumns(20);
        taInvoice.setRows(5);
        jScrollPane1.setViewportView(taInvoice);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnProcess)
                .addGap(112, 112, 112)
                .addComponent(btnClearForm)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCustomerName)
                            .addComponent(lblProductName)
                            .addComponent(lblProductPrice)
                            .addComponent(lblQuantity))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtProductPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(txtProductName)
                                .addComponent(txtCustomerName))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIsMemeber)
                        .addGap(66, 66, 66)
                        .addComponent(rbnYes)
                        .addGap(18, 18, 18)
                        .addComponent(rbnNo)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerName)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProductName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProductPrice))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantity))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIsMemeber)
                    .addComponent(rbnYes)
                    .addComponent(rbnNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnProcess, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnClearForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnProcessActionPerformed
    {//GEN-HEADEREND:event_btnProcessActionPerformed
     NumberFormat curr, perc;
       curr = NumberFormat.getCurrencyInstance();
       perc = NumberFormat.getPercentInstance();
       String customerName = null , productName = null;
       int quantity = 0;
       double prodPrice = 0.0, totalAmount, qd = 0,memberSaveAmt = 0, saveAmt = 0, finalpayment = 0;
       boolean membership;
       final double disc_Perc = 0.35;
       final double member_disc = 0.15;
       
       if (rbnYes.isSelected()){
           membership = true;
       } else  {
           membership= false;
       }
       
       try{
           customerName =txtCustomerName.getText();
           productName = txtProductName.getText();
           prodPrice = Double.parseDouble(txtProductPrice.getText());
           quantity = Integer.parseInt(txtQuantity.getText());
       } catch (NumberFormatException ex){
           JOptionPane.showMessageDialog(this,"Error! Invalid numeric format \n"+ ex.getMessage());
       } catch (IllegalArgumentException ex){
           JOptionPane.showMessageDialog(this,"Error! Invalid product data \n"+ ex.getMessage());
       }
        totalAmount = objProductSales.CalcTotalPrice(prodPrice, quantity);
        
     
        if ( (quantity  >= 3) && membership == true){
            memberSaveAmt = objProductSales.CalcMemberSaveAmt(totalAmount, member_disc, membership);
            saveAmt = objProductSales.CalcsaveAmt(totalAmount, disc_Perc);
            qd = member_disc + disc_Perc ;
            
        }else if ((quantity >= 3) && membership == false){
            saveAmt = objProductSales.CalcsaveAmt(totalAmount, disc_Perc);
            qd = disc_Perc;
            
        }else if ((quantity < 3) && membership == true){
            memberSaveAmt = objProductSales.CalcMemberSaveAmt(totalAmount, member_disc, membership);
            qd = member_disc;
        }else if (( quantity < 3  ) && membership == false){
            saveAmt = 0 ;
            memberSaveAmt = 0;
            qd = 0;
            
        }
        finalpayment = objProductSales.CalcTotalPayment(totalAmount, memberSaveAmt, saveAmt);
        
        taInvoice.setText("-------------Customer Invoice--------------\n");
       // taInvoice.append(objProductSales.toString () + "\n");
       taInvoice.append("Custome Name = " + customerName + "\n");
       taInvoice.append("Product Name = " + productName +"\n");
       taInvoice.append("Quantity = " + quantity + "\n");
        taInvoice.append("Total Price = " + curr.format(totalAmount) + "\n");
        taInvoice.append(" Total Saved Amount = " + curr.format(saveAmt) + "\n");
        taInvoice.append("Total Member Save Amount = " + curr.format(memberSaveAmt)+ "\n");
        taInvoice.append("Total Payment Amount = " + curr.format(finalpayment)+ "\n");
        taInvoice.append("Qualify Discount = " + perc.format(qd) + "\n");


        
    }//GEN-LAST:event_btnProcessActionPerformed

    private void btnClearFormActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnClearFormActionPerformed
    {//GEN-HEADEREND:event_btnClearFormActionPerformed
        this.txtCustomerName.setText("");
        this.txtProductName.setText("");
        this.txtProductPrice.setText("");
        this.txtQuantity.setText("");
        this.rbnYes.setSelected(false);
        this.rbnNo.setSelected(false);
        this.taInvoice.setText("");
    }//GEN-LAST:event_btnClearFormActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Productsale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Productsale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Productsale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Productsale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new Productsale().setVisible(true);
            }
        });
    }
    private void GroupButton(){
        ButtonGroup BG = new ButtonGroup();
        BG.add(rbnNo);
        BG.add(rbnYes);
       rbnNo.setSelected(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearForm;
    private javax.swing.JButton btnProcess;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblIsMemeber;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblProductPrice;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JRadioButton rbnNo;
    private javax.swing.JRadioButton rbnYes;
    private javax.swing.JTextArea taInvoice;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtProductPrice;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
